// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: oberon.flex

import java.io.*;
import exceptions.*;
import java_cup.runtime.*;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class OberonScanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u1100\1\u1200\1\u1300\1\u1400\1\u1100\1\u1500\1\u1600"+
    "\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u1c00\1\u1100\1\u1d00"+
    "\1\u1e00\1\u1f00\12\u2000\1\u2100\1\u2200\1\u2300\1\u2000\1\u2400"+
    "\1\u2500\2\u2000\31\u1100\1\u2600\121\u1100\1\u2700\4\u1100\1\u2800"+
    "\1\u1100\1\u2900\1\u2a00\1\u2b00\1\u2c00\1\u2d00\1\u2e00\53\u1100"+
    "\1\u2f00\10\u3000\31\u2000\1\u1100\1\u3100\1\u3200\1\u1100\1\u3300"+
    "\1\u3400\1\u3500\1\u3600\1\u3700\1\u3800\1\u3900\1\u3a00\3\u2000"+
    "\1\u3b00\1\u3c00\1\u3d00\1\u3e00\1\u3f00\3\u2000\1\u4000\1\u4100"+
    "\4\u2000\1\u4200\11\u2000\3\u1100\1\u4300\1\u4400\13\u2000\4\u1100"+
    "\1\u4500\63\u2000\2\u1100\1\u4600\4\u2000\1\u4700\100\u2000\1\u4800"+
    "\40\u2000\1\u4900\1\u4a00\1\u2000\1\u4b00\1\u4c00\1\u4d00\1\u4e00"+
    "\26\u2000\1\u4f00\21\u2000\246\u1100\1\u5000\20\u1100\1\u5100\1\u5200"+
    "\77\u2000\2\u1100\1\u5200\u0b05\u2000\1\u5300\1\u5400\u02fe\u2000";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\1\1\4\16\0\4\5"+
    "\1\1\2\5\1\6\1\7\1\5\1\10\1\5\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\5\1\20"+
    "\7\21\2\22\1\23\1\24\1\25\1\26\1\27\2\5"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\2\7\1\41\1\42\1\43\1\44\1\45\1\7"+
    "\1\46\1\47\1\50\1\51\1\52\1\53\1\7\1\54"+
    "\1\7\1\55\1\5\1\56\1\5\1\7\1\5\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\2\7\1\41\1\42\1\43\1\44\1\45\1\7\1\46"+
    "\1\47\1\50\1\51\1\52\1\53\1\7\1\54\1\7"+
    "\1\5\1\57\1\5\1\60\6\0\1\61\32\0\2\5"+
    "\4\7\4\5\1\7\2\5\1\0\7\5\1\7\4\5"+
    "\1\7\5\5\27\7\1\5\37\7\1\5\70\7\2\40"+
    "\115\7\1\47\u0142\7\4\5\14\7\16\5\5\7\7\5"+
    "\1\7\1\5\1\7\21\5\160\0\5\7\1\5\2\7"+
    "\2\5\4\7\10\5\1\7\1\5\3\7\1\5\1\7"+
    "\1\5\24\7\1\5\123\7\1\5\213\7\1\5\5\0"+
    "\2\5\236\7\11\5\46\7\2\5\1\7\7\5\47\7"+
    "\7\5\1\7\1\5\55\0\1\5\1\0\1\5\2\0"+
    "\1\5\2\0\1\5\1\0\10\5\33\7\5\5\3\7"+
    "\15\5\5\0\6\5\1\7\4\5\13\0\5\5\53\7"+
    "\37\0\4\5\2\7\1\0\143\7\1\5\1\7\10\0"+
    "\1\5\6\0\2\7\2\0\1\5\4\0\2\7\12\0"+
    "\3\7\2\5\1\7\17\5\1\0\1\7\1\0\36\7"+
    "\33\0\2\5\131\7\13\0\1\7\16\5\12\0\41\7"+
    "\11\0\2\7\4\5\1\7\5\5\26\7\4\0\1\7"+
    "\11\0\1\7\3\0\1\7\5\0\22\5\31\7\3\0"+
    "\104\5\1\7\1\5\13\7\67\5\33\0\1\5\4\0"+
    "\66\7\3\0\1\7\22\0\1\7\7\0\12\7\2\0"+
    "\2\5\12\0\1\5\7\7\1\5\7\7\1\5\3\0"+
    "\1\5\10\7\2\5\2\7\2\5\26\7\1\5\7\7"+
    "\1\5\1\7\3\5\4\7\2\5\1\0\1\7\7\0"+
    "\2\5\2\0\2\5\3\0\1\7\10\5\1\0\4\5"+
    "\2\7\1\5\3\7\2\0\2\5\12\0\4\7\7\5"+
    "\1\7\5\5\3\0\1\5\6\7\4\5\2\7\2\5"+
    "\26\7\1\5\7\7\1\5\2\7\1\5\2\7\1\5"+
    "\2\7\2\5\1\0\1\5\5\0\4\5\2\0\2\5"+
    "\3\0\3\5\1\0\7\5\4\7\1\5\1\7\7\5"+
    "\14\0\3\7\1\0\13\5\3\0\1\5\11\7\1\5"+
    "\3\7\1\5\26\7\1\5\7\7\1\5\2\7\1\5"+
    "\5\7\2\5\1\0\1\7\10\0\1\5\3\0\1\5"+
    "\3\0\2\5\1\7\17\5\2\7\2\0\2\5\12\0"+
    "\1\5\1\7\17\5\3\0\1\5\10\7\2\5\2\7"+
    "\2\5\26\7\1\5\7\7\1\5\2\7\1\5\5\7"+
    "\2\5\1\0\1\7\7\0\2\5\2\0\2\5\3\0"+
    "\10\5\2\0\4\5\2\7\1\5\3\7\2\0\2\5"+
    "\12\0\1\5\1\7\20\5\1\0\1\7\1\5\6\7"+
    "\3\5\3\7\1\5\4\7\3\5\2\7\1\5\1\7"+
    "\1\5\2\7\3\5\2\7\3\5\3\7\3\5\14\7"+
    "\4\5\5\0\3\5\3\0\1\5\4\0\2\5\1\7"+
    "\6\5\1\0\16\5\12\0\11\5\1\7\7\5\3\0"+
    "\1\5\10\7\1\5\3\7\1\5\27\7\1\5\12\7"+
    "\1\5\5\7\3\5\1\7\7\0\1\5\3\0\1\5"+
    "\4\0\7\5\2\0\1\5\2\7\6\5\2\7\2\0"+
    "\2\5\12\0\22\5\2\0\1\5\10\7\1\5\3\7"+
    "\1\5\27\7\1\5\12\7\1\5\5\7\2\5\1\0"+
    "\1\7\7\0\1\5\3\0\1\5\4\0\7\5\2\0"+
    "\7\5\1\7\1\5\2\7\2\0\2\5\12\0\1\5"+
    "\2\7\17\5\2\0\1\5\10\7\1\5\3\7\1\5"+
    "\51\7\2\5\1\7\7\0\1\5\3\0\1\5\4\0"+
    "\1\7\10\5\1\0\10\5\2\7\2\0\2\5\12\0"+
    "\12\5\6\7\2\5\2\0\1\5\22\7\3\5\30\7"+
    "\1\5\11\7\1\5\1\7\2\5\7\7\3\5\1\0"+
    "\4\5\6\0\1\5\1\0\1\5\10\0\22\5\2\0"+
    "\15\5\60\7\1\0\2\7\7\0\4\5\10\7\10\0"+
    "\1\5\12\0\47\5\2\7\1\5\1\7\2\5\2\7"+
    "\1\5\1\7\2\5\1\7\6\5\4\7\1\5\7\7"+
    "\1\5\3\7\1\5\1\7\1\5\1\7\2\5\2\7"+
    "\1\5\4\7\1\0\2\7\6\0\1\5\2\0\1\7"+
    "\2\5\5\7\1\5\1\7\1\5\6\0\2\5\12\0"+
    "\2\5\4\7\40\5\1\7\27\5\2\0\6\5\12\0"+
    "\13\5\1\0\1\5\1\0\1\5\1\0\4\5\2\0"+
    "\10\7\1\5\44\7\4\5\24\0\1\5\2\0\5\7"+
    "\13\0\1\5\44\0\11\5\1\0\71\5\53\7\24\0"+
    "\1\7\12\0\6\5\6\7\4\0\4\7\3\0\1\7"+
    "\3\0\2\7\7\0\3\7\4\0\15\7\14\0\1\7"+
    "\17\0\2\5\46\7\1\5\1\7\5\5\1\7\2\5"+
    "\53\7\1\5\u014d\7\1\5\4\7\2\5\7\7\1\5"+
    "\1\7\1\5\4\7\2\5\51\7\1\5\4\7\2\5"+
    "\41\7\1\5\4\7\2\5\7\7\1\5\1\7\1\5"+
    "\4\7\2\5\17\7\1\5\71\7\1\5\4\7\2\5"+
    "\103\7\2\5\3\0\40\5\20\7\20\5\125\7\14\5"+
    "\u016c\7\2\5\21\7\1\5\32\7\5\5\113\7\3\5"+
    "\3\7\17\5\15\7\1\5\4\7\3\0\13\5\22\7"+
    "\3\0\13\5\22\7\2\0\14\5\15\7\1\5\3\7"+
    "\1\5\2\0\14\5\64\7\40\0\3\5\1\7\3\5"+
    "\2\7\1\0\2\5\12\0\41\5\3\0\2\5\12\0"+
    "\6\5\130\7\10\5\51\7\1\0\1\7\5\5\106\7"+
    "\12\5\35\7\3\5\14\0\4\5\14\0\12\5\12\0"+
    "\36\7\2\5\5\7\13\5\54\7\4\5\21\0\7\7"+
    "\2\0\6\5\12\0\46\5\27\7\5\0\4\5\65\7"+
    "\12\0\1\5\35\0\2\5\13\0\6\5\12\0\15\5"+
    "\1\7\130\5\5\0\57\7\21\0\7\7\4\5\12\0"+
    "\21\5\11\0\14\5\3\0\36\7\15\0\2\7\12\0"+
    "\54\7\16\0\14\5\44\7\24\0\10\5\12\0\3\5"+
    "\3\7\12\0\44\7\122\5\3\0\1\5\25\0\4\7"+
    "\1\0\4\7\3\0\2\7\11\5\300\7\47\0\25\5"+
    "\4\0\26\7\2\5\6\7\2\5\46\7\2\5\6\7"+
    "\2\5\10\7\1\5\1\7\1\5\1\7\1\5\1\7"+
    "\1\5\37\7\2\5\65\7\1\5\7\7\1\5\1\7"+
    "\3\5\3\7\1\5\7\7\3\5\4\7\2\5\6\7"+
    "\4\5\15\7\5\5\3\7\1\5\7\7\16\5\5\0"+
    "\30\5\2\3\5\0\20\5\2\7\23\5\1\7\13\5"+
    "\5\0\5\5\6\0\1\5\1\7\15\5\1\7\20\5"+
    "\15\7\3\5\33\7\25\5\15\0\4\5\1\0\3\5"+
    "\14\0\21\5\1\7\4\5\1\7\2\5\12\7\1\5"+
    "\1\7\3\5\5\7\6\5\1\7\1\5\1\7\1\5"+
    "\1\7\1\5\4\7\1\5\13\7\2\5\4\7\5\5"+
    "\5\7\4\5\1\7\21\5\51\7\u0177\5\57\7\1\5"+
    "\57\7\1\5\205\7\6\5\4\7\3\0\2\7\14\5"+
    "\46\7\1\5\1\7\5\5\1\7\2\5\70\7\7\5"+
    "\1\7\17\5\1\0\27\7\11\5\7\7\1\5\7\7"+
    "\1\5\7\7\1\5\7\7\1\5\7\7\1\5\7\7"+
    "\1\5\7\7\1\5\7\7\1\5\40\0\57\5\1\7"+
    "\325\5\3\7\31\5\11\7\6\0\1\5\5\7\2\5"+
    "\5\7\4\5\126\7\2\5\2\0\2\5\3\7\1\5"+
    "\132\7\1\5\4\7\5\5\51\7\3\5\136\7\21\5"+
    "\33\7\65\5\306\7\112\5\315\7\63\5\215\7\103\5"+
    "\56\7\2\5\15\7\3\5\20\7\12\0\2\7\24\5"+
    "\57\7\1\0\4\5\12\0\1\5\31\7\7\5\1\0"+
    "\120\7\2\0\45\5\11\7\2\5\147\7\2\5\4\7"+
    "\1\5\4\7\14\5\13\7\115\5\12\7\1\0\3\7"+
    "\1\0\4\7\1\0\27\7\5\0\20\5\1\7\7\5"+
    "\64\7\14\5\2\0\62\7\21\0\13\5\12\0\6\5"+
    "\22\0\6\7\3\5\1\7\4\5\12\0\34\7\10\0"+
    "\2\5\27\7\15\0\14\5\35\7\3\5\4\0\57\7"+
    "\16\0\16\5\1\7\12\0\46\5\51\7\16\0\11\5"+
    "\3\7\1\0\10\7\2\0\2\5\12\0\6\5\27\7"+
    "\3\5\1\7\1\0\4\5\60\7\1\0\1\7\3\0"+
    "\2\7\2\0\5\7\2\0\1\7\1\0\1\7\30\5"+
    "\3\7\2\5\13\7\5\0\2\5\3\7\2\0\12\5"+
    "\6\7\2\5\6\7\2\5\6\7\11\5\7\7\1\5"+
    "\7\7\221\5\43\7\10\0\1\5\2\0\2\5\12\0"+
    "\6\5\244\7\14\5\27\7\4\5\61\7\4\5\u0100\3"+
    "\156\7\2\5\152\7\46\5\7\7\14\5\5\7\5\5"+
    "\1\7\1\0\12\7\1\5\15\7\1\5\5\7\1\5"+
    "\1\7\1\5\2\7\1\5\2\7\1\5\154\7\41\5"+
    "\153\7\22\5\100\7\2\5\66\7\50\5\15\7\3\5"+
    "\20\0\20\5\7\0\14\5\2\7\30\5\3\7\31\5"+
    "\1\7\6\5\5\7\1\5\207\7\2\5\1\0\4\5"+
    "\1\7\13\5\12\0\7\5\32\7\4\5\1\7\1\5"+
    "\32\7\13\5\131\7\3\5\6\7\2\5\6\7\2\5"+
    "\6\7\2\5\3\7\3\5\2\7\3\5\2\7\22\5"+
    "\3\0\4\5\14\7\1\5\32\7\1\5\23\7\1\5"+
    "\2\7\1\5\17\7\2\5\16\7\42\5\173\7\105\5"+
    "\65\7\210\5\1\0\202\5\35\7\3\5\61\7\57\5"+
    "\37\7\21\5\33\7\65\5\36\7\2\5\44\7\4\5"+
    "\10\7\1\5\5\7\52\5\236\7\2\5\12\0\126\5"+
    "\6\7\2\5\1\7\1\5\54\7\1\5\2\7\3\5"+
    "\1\7\2\5\27\7\252\5\26\7\12\5\32\7\106\5"+
    "\70\7\6\5\2\7\100\5\1\7\3\0\1\5\2\0"+
    "\5\5\4\0\4\7\1\5\3\7\1\5\33\7\4\5"+
    "\3\0\4\5\1\0\40\5\35\7\203\5\66\7\12\5"+
    "\26\7\12\5\23\7\215\5\111\7\267\5\3\0\65\7"+
    "\17\0\37\5\12\0\20\5\3\0\55\7\13\0\2\5"+
    "\1\0\22\5\31\7\7\5\12\0\6\5\3\0\44\7"+
    "\16\0\1\5\12\0\100\5\3\0\60\7\16\0\4\7"+
    "\13\5\12\0\246\5\53\7\15\0\10\5\12\0\66\5"+
    "\157\7\221\5\143\7\235\5\57\7\321\5\71\7\307\5"+
    "\105\7\13\5\1\7\56\0\20\5\4\0\15\7\140\5"+
    "\2\7\u0163\5\5\0\3\5\26\0\2\5\7\0\36\5"+
    "\4\0\224\5\3\0\273\5\125\7\1\5\107\7\1\5"+
    "\2\7\2\5\1\7\2\5\2\7\2\5\4\7\1\5"+
    "\14\7\1\5\1\7\1\5\7\7\1\5\101\7\1\5"+
    "\4\7\2\5\10\7\1\5\7\7\1\5\34\7\1\5"+
    "\4\7\1\5\5\7\1\5\1\7\3\5\7\7\1\5"+
    "\u0154\7\2\5\31\7\1\5\31\7\1\5\37\7\1\5"+
    "\31\7\1\5\37\7\1\5\31\7\1\5\37\7\1\5"+
    "\31\7\1\5\37\7\1\5\31\7\1\5\10\7\2\5"+
    "\62\0\4\7\1\5\33\7\1\5\2\7\1\5\1\7"+
    "\2\5\1\7\1\5\12\7\1\5\4\7\1\5\1\7"+
    "\1\5\1\7\6\5\1\7\4\5\1\7\1\5\1\7"+
    "\1\5\1\7\1\5\3\7\1\5\2\7\1\5\1\7"+
    "\2\5\1\7\1\5\1\7\1\5\1\7\1\5\1\7"+
    "\1\5\1\7\1\5\2\7\1\5\1\7\2\5\4\7"+
    "\1\5\7\7\1\5\4\7\1\5\4\7\1\5\1\7"+
    "\1\5\12\7\1\5\21\7\5\5\3\7\1\5\5\7"+
    "\1\5\21\7\104\5\327\7\51\5\65\7\13\5\336\7"+
    "\343\5\1\0\36\5\140\0\200\5\360\0\20\5";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[21760];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\0\1\2\1\3\1\4\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\2\15"+
    "\1\16\1\17\1\20\1\21\1\22\15\4\1\23\1\24"+
    "\1\25\3\0\2\26\1\27\2\30\1\31\1\32\1\33"+
    "\5\4\1\34\2\4\1\35\2\4\1\36\1\37\7\4"+
    "\1\0\2\30\4\4\1\40\1\4\1\41\1\4\1\42"+
    "\5\4\1\43\2\4\1\2\1\26\4\4\1\44\4\4"+
    "\1\45\1\4\1\46\1\47\2\4\1\2\1\50\1\51"+
    "\1\4\1\52\1\53\4\4\1\54\1\55\1\26\1\0"+
    "\2\4\1\56\1\4\1\57\1\4\1\26\1\60\1\61"+
    "\1\4\1\62\1\4\1\63";

  private static int [] zzUnpackAction() {
    int [] result = new int[133];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\62\0\62\0\62\0\144\0\62\0\226\0\62"+
    "\0\310\0\62\0\372\0\62\0\62\0\62\0\62\0\u012c"+
    "\0\u015e\0\u0190\0\62\0\u01c2\0\62\0\u01f4\0\u0226\0\u0258"+
    "\0\u028a\0\u02bc\0\u02ee\0\u0320\0\u0352\0\u0384\0\u03b6\0\u03e8"+
    "\0\u041a\0\u044c\0\u047e\0\62\0\62\0\62\0\u04b0\0\372"+
    "\0\u04e2\0\u0514\0\62\0\u0546\0\u0578\0\u05aa\0\62\0\62"+
    "\0\62\0\u05dc\0\u060e\0\u0640\0\u0672\0\u06a4\0\226\0\u06d6"+
    "\0\u0708\0\226\0\u073a\0\u076c\0\226\0\226\0\u079e\0\u07d0"+
    "\0\u0802\0\u0834\0\u0866\0\u0898\0\u08ca\0\u08fc\0\u092e\0\u0960"+
    "\0\u0992\0\u09c4\0\u09f6\0\u0a28\0\226\0\u0a5a\0\226\0\u0a8c"+
    "\0\u0abe\0\u0af0\0\u0b22\0\u0b54\0\u0b86\0\u0bb8\0\226\0\u0bea"+
    "\0\u0c1c\0\u0c4e\0\u0c80\0\u0cb2\0\u0ce4\0\u0d16\0\u0d48\0\226"+
    "\0\u0d7a\0\u0dac\0\u0dde\0\u0e10\0\226\0\u0e42\0\226\0\226"+
    "\0\u0e74\0\u0ea6\0\u0ed8\0\226\0\226\0\u0f0a\0\226\0\226"+
    "\0\u0f3c\0\u0f6e\0\u0fa0\0\u0fd2\0\226\0\u1004\0\u0ed8\0\u1036"+
    "\0\u1068\0\u109a\0\226\0\u10cc\0\226\0\u10fe\0\u1130\0\226"+
    "\0\226\0\u1162\0\226\0\u1194\0\226";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[133];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\5\1\2\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\2\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\3\7\1\34\1\7\1\35\1\7"+
    "\1\36\1\37\1\40\1\7\1\41\1\7\1\42\1\43"+
    "\1\7\1\44\1\45\1\2\1\46\12\4\1\47\1\4"+
    "\1\50\50\4\1\3\6\4\1\47\1\4\1\50\46\4"+
    "\1\7\6\4\1\7\1\4\1\47\1\4\1\50\4\4"+
    "\3\7\5\4\25\7\4\4\1\7\11\4\1\51\1\4"+
    "\1\52\57\4\1\47\1\53\1\50\55\4\1\54\1\4"+
    "\1\47\1\4\1\50\4\4\2\20\1\55\5\4\25\54"+
    "\2\4\1\56\11\4\1\54\1\4\1\47\1\4\1\50"+
    "\4\4\3\21\5\4\25\54\16\4\1\47\1\4\1\50"+
    "\12\4\1\57\44\4\1\47\1\4\1\50\12\4\1\60"+
    "\44\4\1\47\1\4\1\50\12\4\1\61\33\4\1\7"+
    "\6\4\1\7\1\4\1\47\1\4\1\50\4\4\3\7"+
    "\5\4\16\7\1\62\6\7\4\4\2\7\6\4\1\7"+
    "\1\4\1\47\1\4\1\50\4\4\3\7\5\4\4\7"+
    "\1\63\7\7\1\64\10\7\4\4\2\7\6\4\1\7"+
    "\1\4\1\47\1\4\1\50\4\4\3\7\5\4\14\7"+
    "\1\65\10\7\4\4\2\7\6\4\1\7\1\4\1\47"+
    "\1\4\1\50\4\4\3\7\5\4\10\7\1\66\3\7"+
    "\1\67\10\7\4\4\2\7\6\4\1\7\1\4\1\47"+
    "\1\4\1\50\4\4\3\7\5\4\11\7\1\70\1\7"+
    "\1\71\11\7\4\4\2\7\6\4\1\7\1\4\1\47"+
    "\1\4\1\50\4\4\3\7\5\4\5\7\1\72\5\7"+
    "\1\73\11\7\4\4\2\7\6\4\1\7\1\4\1\47"+
    "\1\4\1\50\4\4\3\7\5\4\14\7\1\74\10\7"+
    "\4\4\2\7\6\4\1\7\1\4\1\47\1\4\1\50"+
    "\4\4\3\7\5\4\5\7\1\75\10\7\1\76\6\7"+
    "\4\4\2\7\6\4\1\7\1\4\1\47\1\4\1\50"+
    "\4\4\3\7\5\4\16\7\1\77\6\7\4\4\2\7"+
    "\6\4\1\7\1\4\1\47\1\4\1\50\4\4\3\7"+
    "\5\4\4\7\1\100\20\7\4\4\2\7\6\4\1\7"+
    "\1\4\1\47\1\4\1\50\4\4\3\7\5\4\7\7"+
    "\1\101\14\7\1\102\4\4\2\7\6\4\1\7\1\4"+
    "\1\47\1\4\1\50\4\4\3\7\5\4\1\103\24\7"+
    "\4\4\2\7\6\4\1\7\1\4\1\47\1\4\1\50"+
    "\4\4\3\7\5\4\7\7\1\104\6\7\1\105\6\7"+
    "\4\4\1\7\11\4\1\51\1\4\1\0\57\4\1\51"+
    "\1\4\1\50\46\4\13\52\1\106\46\52\1\54\6\4"+
    "\1\54\1\4\1\47\1\4\1\50\4\4\3\54\5\4"+
    "\25\54\4\4\1\54\7\4\1\54\1\4\1\47\1\4"+
    "\1\50\4\4\2\107\1\55\5\4\25\54\2\4\1\56"+
    "\13\4\1\47\1\4\1\50\4\4\2\110\1\56\34\4"+
    "\1\56\2\4\1\7\6\4\1\7\1\4\1\47\1\4"+
    "\1\50\4\4\3\7\5\4\16\7\1\111\6\7\4\4"+
    "\2\7\6\4\1\7\1\4\1\47\1\4\1\50\4\4"+
    "\3\7\5\4\6\7\1\112\16\7\4\4\2\7\6\4"+
    "\1\7\1\4\1\47\1\4\1\50\4\4\3\7\5\4"+
    "\14\7\1\113\10\7\4\4\2\7\6\4\1\7\1\4"+
    "\1\47\1\4\1\50\4\4\3\7\5\4\13\7\1\114"+
    "\11\7\4\4\2\7\6\4\1\7\1\4\1\47\1\4"+
    "\1\50\4\4\3\7\5\4\22\7\1\115\2\7\4\4"+
    "\2\7\6\4\1\7\1\4\1\47\1\4\1\50\4\4"+
    "\3\7\5\4\17\7\1\116\5\7\4\4\2\7\6\4"+
    "\1\7\1\4\1\47\1\4\1\50\4\4\3\7\5\4"+
    "\3\7\1\117\21\7\4\4\2\7\6\4\1\7\1\4"+
    "\1\47\1\4\1\50\4\4\3\7\5\4\20\7\1\120"+
    "\4\7\4\4\2\7\6\4\1\7\1\4\1\47\1\4"+
    "\1\50\4\4\3\7\5\4\3\7\1\121\21\7\4\4"+
    "\2\7\6\4\1\7\1\4\1\47\1\4\1\50\4\4"+
    "\3\7\5\4\14\7\1\122\10\7\4\4\2\7\6\4"+
    "\1\7\1\4\1\47\1\4\1\50\4\4\3\7\5\4"+
    "\1\123\1\7\1\124\22\7\4\4\2\7\6\4\1\7"+
    "\1\4\1\47\1\4\1\50\4\4\3\7\5\4\4\7"+
    "\1\125\20\7\4\4\2\7\6\4\1\7\1\4\1\47"+
    "\1\4\1\50\4\4\3\7\5\4\15\7\1\126\7\7"+
    "\4\4\2\7\6\4\1\7\1\4\1\47\1\4\1\50"+
    "\4\4\3\7\5\4\16\7\1\127\6\7\4\4\2\7"+
    "\6\4\1\7\1\4\1\47\1\4\1\50\4\4\3\7"+
    "\5\4\10\7\1\130\14\7\4\4\2\7\6\4\1\7"+
    "\1\4\1\47\1\4\1\50\4\4\3\7\5\4\10\7"+
    "\1\131\14\7\4\4\1\7\12\52\1\132\1\133\46\52"+
    "\7\4\1\54\1\4\1\47\1\4\1\50\4\4\3\107"+
    "\5\4\25\54\16\4\1\47\1\4\1\50\4\4\3\110"+
    "\37\4\1\7\6\4\1\7\1\4\1\47\1\4\1\50"+
    "\4\4\3\7\5\4\1\134\24\7\4\4\2\7\6\4"+
    "\1\7\1\4\1\47\1\4\1\50\4\4\3\7\5\4"+
    "\10\7\1\135\14\7\4\4\2\7\6\4\1\7\1\4"+
    "\1\47\1\4\1\50\4\4\3\7\5\4\11\7\1\136"+
    "\13\7\4\4\2\7\6\4\1\7\1\4\1\47\1\4"+
    "\1\50\4\4\3\7\5\4\17\7\1\137\5\7\4\4"+
    "\2\7\6\4\1\7\1\4\1\47\1\4\1\50\4\4"+
    "\3\7\5\4\4\7\1\140\3\7\1\141\14\7\4\4"+
    "\2\7\6\4\1\7\1\4\1\47\1\4\1\50\4\4"+
    "\3\7\5\4\4\7\1\142\20\7\4\4\2\7\6\4"+
    "\1\7\1\4\1\47\1\4\1\50\4\4\3\7\5\4"+
    "\21\7\1\143\3\7\4\4\2\7\6\4\1\7\1\4"+
    "\1\47\1\4\1\50\4\4\3\7\5\4\2\7\1\144"+
    "\22\7\4\4\2\7\6\4\1\7\1\4\1\47\1\4"+
    "\1\50\4\4\3\7\5\4\3\7\1\145\21\7\4\4"+
    "\2\7\6\4\1\7\1\4\1\47\1\4\1\50\4\4"+
    "\3\7\5\4\14\7\1\146\10\7\4\4\2\7\6\4"+
    "\1\7\1\4\1\47\1\4\1\50\4\4\3\7\5\4"+
    "\13\7\1\147\11\7\4\4\2\7\6\4\1\7\1\4"+
    "\1\47\1\4\1\50\4\4\3\7\5\4\4\7\1\150"+
    "\20\7\4\4\2\7\6\4\1\7\1\4\1\47\1\4"+
    "\1\50\4\4\3\7\5\4\11\7\1\151\13\7\4\4"+
    "\2\7\6\4\1\7\1\4\1\47\1\4\1\50\4\4"+
    "\3\7\5\4\20\7\1\152\4\7\4\4\1\7\62\0"+
    "\12\52\1\153\1\133\46\52\1\7\6\4\1\7\1\4"+
    "\1\47\1\4\1\50\4\4\3\7\5\4\24\7\1\154"+
    "\4\4\2\7\6\4\1\7\1\4\1\47\1\4\1\50"+
    "\4\4\3\7\5\4\13\7\1\155\11\7\4\4\2\7"+
    "\6\4\1\7\1\4\1\47\1\4\1\50\4\4\3\7"+
    "\5\4\4\7\1\156\20\7\4\4\2\7\6\4\1\7"+
    "\1\4\1\47\1\4\1\50\4\4\3\7\5\4\20\7"+
    "\1\157\4\7\4\4\2\7\6\4\1\7\1\4\1\47"+
    "\1\4\1\50\4\4\3\7\5\4\5\7\1\160\17\7"+
    "\4\4\2\7\6\4\1\7\1\4\1\47\1\4\1\50"+
    "\4\4\3\7\5\4\6\7\1\161\16\7\4\4\2\7"+
    "\6\4\1\7\1\4\1\47\1\4\1\50\4\4\3\7"+
    "\5\4\11\7\1\162\13\7\4\4\2\7\6\4\1\7"+
    "\1\4\1\47\1\4\1\50\4\4\3\7\5\4\4\7"+
    "\1\163\20\7\4\4\2\7\6\4\1\7\1\4\1\47"+
    "\1\4\1\50\4\4\3\7\5\4\16\7\1\164\6\7"+
    "\4\4\2\7\6\4\1\7\1\4\1\47\1\4\1\50"+
    "\4\4\3\7\5\4\4\7\1\165\20\7\4\4\2\7"+
    "\6\4\1\7\1\4\1\47\1\4\1\50\4\4\3\7"+
    "\5\4\4\7\1\166\20\7\4\4\1\7\13\167\1\170"+
    "\46\167\1\7\6\4\1\7\1\4\1\47\1\4\1\50"+
    "\4\4\3\7\5\4\1\171\24\7\4\4\2\7\6\4"+
    "\1\7\1\4\1\47\1\4\1\50\4\4\3\7\5\4"+
    "\4\7\1\172\20\7\4\4\2\7\6\4\1\7\1\4"+
    "\1\47\1\4\1\50\4\4\3\7\5\4\4\7\1\173"+
    "\20\7\4\4\2\7\6\4\1\7\1\4\1\47\1\4"+
    "\1\50\4\4\3\7\5\4\3\7\1\174\21\7\4\4"+
    "\2\7\6\4\1\7\1\4\1\47\1\4\1\50\4\4"+
    "\3\7\5\4\3\7\1\175\21\7\4\4\2\7\6\4"+
    "\1\7\1\4\1\47\1\4\1\50\4\4\3\7\5\4"+
    "\11\7\1\176\13\7\4\4\1\7\12\167\1\0\1\177"+
    "\46\167\1\7\6\4\1\7\1\4\1\47\1\4\1\50"+
    "\4\4\3\7\5\4\13\7\1\200\11\7\4\4\2\7"+
    "\6\4\1\7\1\4\1\47\1\4\1\50\4\4\3\7"+
    "\5\4\16\7\1\201\6\7\4\4\2\7\6\4\1\7"+
    "\1\4\1\47\1\4\1\50\4\4\3\7\5\4\21\7"+
    "\1\202\3\7\4\4\2\7\6\4\1\7\1\4\1\47"+
    "\1\4\1\50\4\4\3\7\5\4\13\7\1\203\11\7"+
    "\4\4\1\7\13\167\1\177\46\167\1\7\6\4\1\7"+
    "\1\4\1\47\1\4\1\50\4\4\3\7\5\4\16\7"+
    "\1\204\6\7\4\4\2\7\6\4\1\7\1\4\1\47"+
    "\1\4\1\50\4\4\3\7\5\4\4\7\1\205\20\7"+
    "\4\4\1\7";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4550];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\1\1\0\42\1\3\0\34\1\1\0\23\1"+
    "\1\11\35\1\1\0\15\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[133];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
	int get_line(){
		return yyline;
	}
	int get_column(){
		return yycolumn;
	}
	private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public OberonScanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException, LexicalException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { 	return symbol(Symbols.EOF);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new IllegalSymbolException();
            }
            // fall through
          case 52: break;
          case 2:
            { 
            }
            // fall through
          case 53: break;
          case 3:
            { return symbol(Symbols.NOTEQUAL);
            }
            // fall through
          case 54: break;
          case 4:
            { if (yylength()>24)
									throw new IllegalIdentifierLengthException();
								else
									return symbol(Symbols.IDENTIFIER, yytext());
            }
            // fall through
          case 55: break;
          case 5:
            { return symbol(Symbols.AND);
            }
            // fall through
          case 56: break;
          case 6:
            { return symbol(Symbols.LPAREN);
            }
            // fall through
          case 57: break;
          case 7:
            { return symbol(Symbols.RPAREN);
            }
            // fall through
          case 58: break;
          case 8:
            { return symbol(Symbols.TIMES);
            }
            // fall through
          case 59: break;
          case 9:
            { return symbol(Symbols.PLUS);
            }
            // fall through
          case 60: break;
          case 10:
            { return symbol(Symbols.COMMA);
            }
            // fall through
          case 61: break;
          case 11:
            { return symbol(Symbols.MINUS);
            }
            // fall through
          case 62: break;
          case 12:
            { return symbol(Symbols.DOT);
            }
            // fall through
          case 63: break;
          case 13:
            { if (yylength() > 12)
									throw new IllegalIntegerRangeException();
								else
									return symbol(Symbols.NUMBER, yytext());
            }
            // fall through
          case 64: break;
          case 14:
            { return symbol(Symbols.COLON);
            }
            // fall through
          case 65: break;
          case 15:
            { return symbol(Symbols.SEMI);
            }
            // fall through
          case 66: break;
          case 16:
            { return symbol(Symbols.LT);
            }
            // fall through
          case 67: break;
          case 17:
            { return symbol(Symbols.EQUAL);
            }
            // fall through
          case 68: break;
          case 18:
            { return symbol(Symbols.GT);
            }
            // fall through
          case 69: break;
          case 19:
            { return symbol(Symbols.LBRACKET);
            }
            // fall through
          case 70: break;
          case 20:
            { return symbol(Symbols.RBRACKET);
            }
            // fall through
          case 71: break;
          case 21:
            { return symbol(Symbols.NOT);
            }
            // fall through
          case 72: break;
          case 22:
            { throw new MismatchedCommentException();
            }
            // fall through
          case 73: break;
          case 23:
            { throw new IllegalIntegerException();
            }
            // fall through
          case 74: break;
          case 24:
            { throw new IllegalOctalException();
            }
            // fall through
          case 75: break;
          case 25:
            { return symbol(Symbols.ASSIGN);
            }
            // fall through
          case 76: break;
          case 26:
            { return symbol(Symbols.LE);
            }
            // fall through
          case 77: break;
          case 27:
            { return symbol(Symbols.GE);
            }
            // fall through
          case 78: break;
          case 28:
            { return symbol(Symbols.DO);
            }
            // fall through
          case 79: break;
          case 29:
            { return symbol(Symbols.IF);
            }
            // fall through
          case 80: break;
          case 30:
            { return symbol(Symbols.OF);
            }
            // fall through
          case 81: break;
          case 31:
            { return symbol(Symbols.OR);
            }
            // fall through
          case 82: break;
          case 32:
            { return symbol(Symbols.DIVIDE);
            }
            // fall through
          case 83: break;
          case 33:
            { return symbol(Symbols.END);
            }
            // fall through
          case 84: break;
          case 34:
            { return symbol(Symbols.MOD);
            }
            // fall through
          case 85: break;
          case 35:
            { return symbol(Symbols.VAR);
            }
            // fall through
          case 86: break;
          case 36:
            { return symbol(Symbols.ELSE);
            }
            // fall through
          case 87: break;
          case 37:
            { return symbol(Symbols.READ);
            }
            // fall through
          case 88: break;
          case 38:
            { return symbol(Symbols.THEN);
            }
            // fall through
          case 89: break;
          case 39:
            { return symbol(Symbols.TYPE);
            }
            // fall through
          case 90: break;
          case 40:
            { return symbol(Symbols.ARRAY);
            }
            // fall through
          case 91: break;
          case 41:
            { return symbol(Symbols.BEGIN);
            }
            // fall through
          case 92: break;
          case 42:
            { return symbol(Symbols.CONST);
            }
            // fall through
          case 93: break;
          case 43:
            { return symbol(Symbols.ELSIF);
            }
            // fall through
          case 94: break;
          case 44:
            { return symbol(Symbols.WHILE);
            }
            // fall through
          case 95: break;
          case 45:
            { return symbol(Symbols.WRITE);
            }
            // fall through
          case 96: break;
          case 46:
            { return symbol(Symbols.MODULE);
            }
            // fall through
          case 97: break;
          case 47:
            { return symbol(Symbols.RECORD);
            }
            // fall through
          case 98: break;
          case 48:
            { return symbol(Symbols.BOOLEAN);
            }
            // fall through
          case 99: break;
          case 49:
            { return symbol(Symbols.INTEGER);
            }
            // fall through
          case 100: break;
          case 50:
            { return symbol(Symbols.WRITELN);
            }
            // fall through
          case 101: break;
          case 51:
            { return symbol(Symbols.PROCEDURE);
            }
            // fall through
          case 102: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
