
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Symbols {
  /* terminals */
  public static final int DIVIDE = 26;
  public static final int LBRACKET = 41;
  public static final int CONST = 18;
  public static final int GE = 33;
  public static final int ELSIF = 8;
  public static final int INTEGER = 13;
  public static final int NOTEQUAL = 29;
  public static final int SEMI = 43;
  public static final int LPAREN = 39;
  public static final int ARRAY = 19;
  public static final int MINUS = 24;
  public static final int WRITE = 21;
  public static final int RPAREN = 40;
  public static final int NOT = 36;
  public static final int AND = 34;
  public static final int LT = 30;
  public static final int RECORD = 17;
  public static final int TYPE = 16;
  public static final int OR = 35;
  public static final int COMMA = 44;
  public static final int BEGIN = 4;
  public static final int PLUS = 23;
  public static final int ASSIGN = 37;
  public static final int IF = 6;
  public static final int WRITELN = 22;
  public static final int DOT = 45;
  public static final int LE = 31;
  public static final int OF = 12;
  public static final int EOF = 0;
  public static final int BOOLEAN = 14;
  public static final int RBRACKET = 42;
  public static final int EQUAL = 28;
  public static final int error = 1;
  public static final int NUMBER = 47;
  public static final int MOD = 27;
  public static final int MODULE = 2;
  public static final int TIMES = 25;
  public static final int COLON = 38;
  public static final int ELSE = 9;
  public static final int READ = 20;
  public static final int WHILE = 10;
  public static final int THEN = 7;
  public static final int END = 5;
  public static final int GT = 32;
  public static final int VAR = 15;
  public static final int PROCEDURE = 3;
  public static final int DO = 11;
  public static final int IDENTIFIER = 46;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MODULE",
  "PROCEDURE",
  "BEGIN",
  "END",
  "IF",
  "THEN",
  "ELSIF",
  "ELSE",
  "WHILE",
  "DO",
  "OF",
  "INTEGER",
  "BOOLEAN",
  "VAR",
  "TYPE",
  "RECORD",
  "CONST",
  "ARRAY",
  "READ",
  "WRITE",
  "WRITELN",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "MOD",
  "EQUAL",
  "NOTEQUAL",
  "LT",
  "LE",
  "GT",
  "GE",
  "AND",
  "OR",
  "NOT",
  "ASSIGN",
  "COLON",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "SEMI",
  "COMMA",
  "DOT",
  "IDENTIFIER",
  "NUMBER"
  };
}

